name: Move new issues

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: read
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Main
          column: Todo
          repo-token: ${{ secrets.GITHUB_TOKEN }}
