name: Move new issues

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.2
        with:
          project: TODO
          column: Todo
          repo-token: ${{ secrets.GITHUB_TOKEN }}
